In [1]:
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[46:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
46                5.1               3.8                1.6               0.2   
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
46      setosa  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [14]:
from sklearn.svm import SVC

model = SVC(kernel='rbf', C=30, gamma='auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.9777777777777777

In [18]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='linear', C=10, gamma='auto'), iris.data, iris.target, cv=5)


array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [19]:
cross_val_score(SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)


array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [20]:

cross_val_score(SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

Average Scores

In [23]:
import numpy as np
kernels = ['rbf','linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel=kval, C=cval, gamma = 'auto'), iris.data, iris.target, cv=5)
        avg_scores[kval + "_" + str(cval)] = np.average(cv_scores)
avg_scores

{'rbf_1': np.float64(0.9800000000000001),
 'rbf_10': np.float64(0.9800000000000001),
 'rbf_20': np.float64(0.9666666666666668),
 'linear_1': np.float64(0.9800000000000001),
 'linear_10': np.float64(0.9733333333333334),
 'linear_20': np.float64(0.9666666666666666)}

Grid Search CV

In [26]:
from sklearn.model_selection import GridSearchCV

cif = GridSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel':['rbf', 'linear']
}, cv=5, return_train_score=False)

cif.fit(iris.data, iris.target)
cif.cv_results_

{'mean_fit_time': array([0.0009973 , 0.00060472, 0.00110536, 0.00071154, 0.00030189,
        0.00090137]),
 'std_fit_time': array([4.67932527e-06, 4.93796652e-04, 2.04281925e-04, 6.10379680e-04,
        4.00360849e-04, 4.92619464e-04]),
 'mean_score_time': array([0.00070262, 0.00100098, 0.00101175, 0.00120378, 0.0007987 ,
        0.00019951]),
 'std_score_time': array([4.00318895e-04, 1.02076570e-05, 9.90467799e-06, 4.13194104e-04,
        3.99975516e-04, 3.99017334e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
 

In [27]:
df = pd.DataFrame(cif.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.000997      0.000005         0.000703        0.000400        1   
1       0.000605      0.000494         0.001001        0.000010        1   
2       0.001105      0.000204         0.001012        0.000010       10   
3       0.000712      0.000610         0.001204        0.000413       10   
4       0.000302      0.000400         0.000799        0.000400       20   
5       0.000901      0.000493         0.000200        0.000399       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [28]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [29]:
cif.best_score_

np.float64(0.9800000000000001)

In [30]:
cif.best_params_

{'C': 1, 'kernel': 'rbf'}

In [31]:
from sklearn.model_selection import RandomizedSearchCV

cif = RandomizedSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel':['rbf', 'linear']
}, cv=5, return_train_score=False,n_iter=2)

cif.fit(iris.data, iris.target)
cif.cv_results_

{'mean_fit_time': array([0.00118818, 0.00151405]),
 'std_fit_time': array([0.0007301, 0.0015789]),
 'mean_score_time': array([0.00111785, 0.00112562]),
 'std_score_time': array([0.00067559, 0.00025058]),
 'param_kernel': masked_array(data=['rbf', 'rbf'],
              mask=[False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[10, 1],
              mask=[False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 10}, {'kernel': 'rbf', 'C': 1}],
 'split0_test_score': array([0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.98, 0.98]),
 'std_test_score': array([0.01632993, 0.01632993]),
 'rank_test_score': array([1, 1], dtype=int32)}

In [33]:
pd.DataFrame(cif.cv_results_)[['param_C','param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       10          rbf             0.98
1        1          rbf             0.98